var data = {
    potions: {
        potion_of_healing: {
            items: ["glistering_melon_slice"],
            extended: [false],
            enhanced: [true, "Instant", "II"],
            effects: ["instant_health"],
            length: "Instant",
            lingering: ["Instant","","Instant"],
        },
        potion_of_fire_resistance: {
            items: ["magma_cream"],
            extended: [true, "8:00", "+"],
            enhanced: [false],
            effects: ["fire_resistance"],
            length: "03:00",
            lingering: ["00:45","02:00",""],
        },
        potion_of_regeneration: {
            items: ["ghast_tear"],
            extended: [true, "01:30", "+"],
            enhanced: [true, "00:22.5", "II"],
            effects: ["regeneration"],
            length: "00:45",
            lingering: ["00:11","00:22","00:05"],
        },
        potion_of_strength: {
            items: ["blaze_powder"],
            extended: [true, "08:00", "+"],
            enhanced: [true, "01:30", "II"],
            effects: ["strength"],
            length: "03:00",
            lingering: ["00:45","02:00","00:22"],
        },
        potion_of_swiftness: {
            items: ["sugar"],
            extended: [true, "08:00", "+"],
            enhanced: [true, "01:30", "II"],
            effects: ["speed"],
            length: "03:00",
            lingering: ["00:45","02:00","00:22"],
        },
        potion_of_night_vision: {
            items: ["golden_carrot"],
            extended: [true, "08:00", "+"],
            enhanced: [false],
            effects: ["night_vision"],
            length: "03:00",
            lingering: ["00:45","02:00",""],
        },
        potion_of_invisibility: {
            items: ["golden_carrot", "fermented_spider_eye"],
            extended: [true, "08:00", "+"],
            enhanced: [false],
            effects: ["invisibility"],
            length: "03:00",
            lingering: ["00:45","02:00",""],
        },
        potion_of_breathing: {
            items: ["pufferfish"],
            extended: [true, "08:00", "+"],
            enhanced: false,
            effects: ["water_breathing"],
            length: "03:00",
            lingering: ["00:45","02:00",""],
        },
        potion_of_leaping: {
            items: ["rabbits_foot"],
            extended: [true, "08:00", "+"],
            enhanced: [true, "01:30", "II"],
            effects: ["jump_boost"],
            length: "03:00",
            lingering: ["00:45","02:00","00:22"],
        },
        potion_of_slow_falling: {
            items: ["phantom_membrane"],
            extended: [true, "04:00", "+"],
            enhanced: false,
            effects: ["slow_falling"],
            length: "01:30",
            lingering: ["00:22","01:00",""],
        },
        potion_of_poison: {
            items: ["spider_eye"],
            extended: [true, "01:30", "+"],
            enhanced: [true, "00:21.6", "II"],
            effects: ["poison"],
            length: "00:45",
            lingering: ["00:11","00:22","00:05"],
        },
        potion_of_weakness: {
            items: ["fermented_spider_eye"],
            extended: [true, "04:00", "+"],
            enhanced: [false],
            effects: ["weakness"],
            length: "01:30",
            lingering: ["00:22","01:00",""],
        },
        potion_of_harming: {
            items: ["glistering_melon_slice", "fermented_spider_eye"],
            extended: [false],
            enhanced: [true, "Instant", "II"],
            effects: ["instant_damage"],
            length: "Instant",
            lingering: ["Instant","","Instant"],
        },
        potion_of_slowness: {
            items: ["sugar", "fermented_spider_eye"],
            extended: [true, "04:00", "+"],
            enhanced: [true, "00:20", "IV"],
            effects: ["slowness"],
            length: "01:30",
            lingering: ["00:22","01:00","00:05"],
        },
        potion_of_oozing: {
            items: ["slime_block"],
            extended: false,
            enhanced: false,
            effects: ["oozing"],
            length: "03:00",
            lingering: ["00:45","",""],
        },
        potion_of_weaving: {
            items: ["cobweb"],
            extended: false,
            enhanced: false,
            effects: ["weaving"],
            length: "03:00",
            lingering: ["00:45","",""],
        },
        potion_of_infestation: {
            items: ["stone"],
            extended: false,
            enhanced: false,
            effects: ["infestation"],
            length: "03:00",
            lingering: ["00:45","",""],
        },
        potion_of_wind_charge: {
            items: ["breeze_rod"],
            extended: false,
            enhanced: false,
            effects: ["wind_charged"],
            length: "03:00",
            lingering: ["00:45","",""],
        },
        potion_of_turtle_master: {
            items: ["turtle_shell"],
            extended: [true, "00:40", "+"],
            enhanced: [true, "00:20", "II"],
            effects: ["resistance", "slowness"],
            length: "00:20",
            lingering: ["00:05","00:10","00:05"],
        }
    },
    items: [
        'water_bottle',
        'nether_wart',
        'gunpowder',
        'dragons_breath',
        'fermented_spider_eye',
        'glowstone_dust',
        'redstone_dust',
        'blaze_powder',

        'sugar',
        "rabbits_foot",
        'blaze_powder',
        'glistering_melon_slice',
        'spider_eye',
        'ghast_tear',
        'magma_cream',
        'pufferfish',
        'golden_carrot',
        'turtle_shell',
        'phantom_membrane',
        'breeze_rod',
        'cobweb',
        'slime_block',
        'stone'
    ]
};
